#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define IDR_MYMENU 101
#define IDI_MYICON 201
#define IDB_RELOAD_MAP 103
#define IDB_WRITE_MAP 104
#define IDD_SELECTMAP 301
#define IDD_SIZE_CBO    102
#define IDC_COMBOBOX_TEXT 1000

#define IDD_ABOUT 301

#define IDC_STATIC -1

#define ID_FILE_OPEN 9000
#define ID_FILE_EXIT 9001
#define ID_STUFF_GO 9002

#endif // RESOURCE_H_INCLUDED
